### PR TITLE
adding a new sample sheet for microbiome samples

### PR DESCRIPTION
**Pull request by sjanssen2**

### CODE REVIEW

**Comment by deyazoubi** [comment]
is it ok if there are 2 indexes [index, index2]?

**Comment by sjanssen2** [comment]
@deyazoubi the illumina barcodes can only demultiplex 12 samples, but we have 8*12=96. Thus, we are using one barcode at the 5' end and another at the 3' end. Thus, two barcodes are required which works perfectly with bcl2fastq.
We only have this situation for microbiome profiling, not for the regular spike samples.

**Comment by LayalYasin** [comment]
looks fine

**Comment by sjanssen2** [comment]
perfect. That is exactly how we should add changes to spike :-) Thanks to both of you!

**Comment by deyazoubi** [comment]
yes
 
--

Deya Alzoubi

Computational Cell Biology

Universitätsstr. 1
Gebäude: 25.02
Etage/Raum: O2.31
Tel.: +49 211 81-15835
Fax: +49 211 81-15767

**Pull request merged**
