### PR TITLE
I manually changed barcodes for lane3 following Suji<92>s advice. 

### PR DESCRIPTION
**Pull request by sjanssen2**
But this comes with the very high risk of introducing a sample swap.

Once this PR is merged, we need to re-execute the demultiplexing process via spike!

### CODE REVIEW

**Comment by LayalYasin** [comment]
why would a sample swap happen in this case? the barcodes seem distinct to me, or is there another cause?

**Comment by sjanssen2** [comment]
because it is unclear if the first barcode really belongs to the first sample in our samplesheet. We might get this wrong and Suji told me she already lost her wetlab notes :-/

**Comment by deyazoubi** [comment]
git pull origin master ..... done
copy the sample sheet to "/gpfs/project/projects/spike/Inputs/SampleSheets/" ... done
run the pipeline .... done
transfer fastq data to external hard drive

**Comment by sjanssen2** [comment]
This is how you can make it a to do list

**Pull request merged**
